name: Go Coverage
on: [pull_request]
permissions:
  contents: read

jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: '1.19.0'
        id: go

      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Build
        run: go build -v ./...

      - name: Test With Coverage
        run: |
          for d in request core coremain plugin test; do \
             ( cd $d; go test -coverprofile=cover.out -covermode=atomic -race ./...; [ -f cover.out ] && cat cover.out >> ../coverage.txt ); \
          done

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
